echo off
rem test_hvhdl_ethernet.vhd

call fpga_communication/ghdl_compile_fpga_communication.bat fpga_communication/
call source/hVHDL_gigabit_ethernet/ghdl_compile_ethernet.bat source/hVHDL_gigabit_ethernet/
