
[libraries.hvhdl_gigabit_ethernet]
files = [ 
"./source/hVHDL_gigabit_ethernet/mdio_driver/mdio_three_state_io_driver/mdio_three_state_io_driver_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/mdio_driver/mdio_driver_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/mdio_driver/mdio_driver_internal_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/mdio_driver/mmd_access_functions_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/mdio_driver/mdio_driver.vhd",

"./source/hVHDL_gigabit_ethernet/ethernet_rx_ddio/efinix_fpga_ddio_record.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_rx_ddio/ethernet_rx_ddio_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_rx_ddio/efinix_rx_ddio.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_clocks_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_common/PCK_CRC_32_D8.vhd",

"./source/hVHDL_gigabit_ethernet/ethernet_common/dual_port_ethernet_ram/ethernet_frame_ram_read_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_common/dual_port_ethernet_ram/ethernet_frame_ram_write_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_common/dual_port_ethernet_ram/dpram.vhd",

"./source/hVHDL_gigabit_ethernet/fifo/fifo_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/fifo/fifo.vhd",

"./source/hVHDL_gigabit_ethernet/frame_transmitter/frame_transmitter_pkg.vhd",

"./source/hVHDL_gigabit_ethernet/ethernet_frame_receiver/ethernet_frame_receiver_pkg.vhd",

"./source/hVHDL_gigabit_ethernet/ethernet_tx/ethernet_tx_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_tx/ethernet_tx.vhd",

"./source/hVHDL_gigabit_ethernet/ethernet_rx/ethernet_rx_pkg.vhd",
"./source/hVHDL_gigabit_ethernet/ethernet_rx/ethernet_rx.vhd",

"./source/hVHDL_gigabit_ethernet/testbenches/transmit_test_pkg.vhd",

"./fpga_communication/hVHDL_fpga_interconnect/interconnect_configuration/data_15_address_15_bit_pkg.vhd",
"./fpga_communication/hVHDL_fpga_interconnect/fpga_interconnect_pkg.vhd",
]



